#  config:
#    import: http://localhost:8888/


management:
  endpoints:
    web:
      exposure:
        include: "*"
#          - refresh, bus-refresh, beans, env https://soshace.com/spring-cloud-config-refresh-strategies/